### ISSUE TITLE
Images lost after "stack-task" filter when parameter "number" is not a factor of number of input images

### ISSUE THREAD

**Issue by harishkumar-harihara** [ufo-kit/ufo-filters#210] opened 2021-05-17 10:46 UTC
Hello,

I send N images (in a stream) via the "stack" filter's "number" parameter. If the N is not a factor of the total number of input images, I find the remaining images lost at this stage and not forwarded to the next filter.

For example, when the total number of images is 256 & the stack parameter "number" is 10, then the last six images are not received at the next filter.

As I debugged, I find the below condition leaves out the remaining images.
https://github.com/ufo-kit/ufo-filters/blob/d1abb276665ed3b6f59de2b6b0301b08f133115a/src/ufo-stack-task.c#L119

Also, the `ufo_stack_task_get_requisition` method is called once, thereby unable to modify the above condition (to replace `"priv->n_items" with dim[2]`) to suit the available images in the stream. 

I tried to create the remaining images in `ufo_stack_task_generate`, but it generated 10 instead of 6 images. 

Best regards,
Harish Kumar Harihara Subramanian

**Comment by tfarago** [comment] 2021-05-20 15:01
Dear Harish,
the problem is that `stack` has no way of knowing how many images it will get from its source, so I don't see a quickfix for this. Please make sure you use a multiple of `number` images for now, I will get back to this, do not close the issue please.

**Comment by harishkumar-harihara** [comment] 2021-05-20 15:09
Dear Thomas,

Thanks for your response. I am looking forward to hearing from you on the issue.

**Closed** 2021-10-06 06:51 UTC
